version: '2'
services:
    jhipstertasksdemo-app:
        image: jhipstertasksdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstertasksdemo-mysql:3306/jhipstertasksdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertasksdemo-mysql:
        extends:
            file: mysql.yml
            service: jhipstertasksdemo-mysql
